title: "SQLWATCH Docs"
description: "SQLWATCH is an open source, community driven SQL Server performance monitor."

# build settings
exclude: ["script", "vendor", "bower.json", "Gemfile", "Gemfile.lock", "Rakefile", "readme.md", "package.json", "node_modules"]
